CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  domain TEXT NOT NULL,
  googleManagerId TEXT NOT NULL,
  password TEXT NOT NULL,
  isOnline BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  userId INTEGER NOT NULL,
  name TEXT NOT NULL,
  address TEXT,
  zip TEXT,
  city TEXT,
  phone TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS suppliers (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  userId INTEGER NOT NULL,
  name TEXT NOT NULL,
  address TEXT,
  zip TEXT,
  city TEXT,
  phone TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS invoices_out (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  customerId INTEGER NOT NULL,
  date TIMESTAMP,
  status INTEGER NOT NULL DEFAULT 0,
  discount DECIMAL(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoices_in (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  supplierId INTEGER NOT NULL,
  date TIMESTAMP,
  status INTEGER NOT NULL DEFAULT 0,
  discount DECIMAL(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  unit TEXT
);

CREATE TABLE IF NOT EXISTS invoice_item_relations (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  invoiceId INTEGER NOT NULL,
  itemId INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS contents (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  userId INTEGER NOT NULL,
  parentId INTEGER,
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT,
  date TIMESTAMP,
  url TEXT,
  image TEXT,
  orderIndex INTEGER NOT NULL DEFAULT 0
);